name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nimbusml --tag nimbusml:$(date +%s)
    - name: Test the Docker image
      run: docker run --rm -t nimbusml
