name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag nimbusml --tag nimbusml:$(date +%s)
      - name: Docker image details
        run: docker image ls
      - name: Test the Docker image
        run: docker run --rm -t nimbusml
